/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartoesIndexRouteImport } from './routes/cartoes.index'
import { Route as GastosIndexRouteImport } from './routes/gastos.index'
import { Route as GastosIdRouteImport } from './routes/gastos.$id'
import { Route as GastosNovoRouteImport } from './routes/gastos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesIndexRoute = CartoesIndexRouteImport.update({
  id: '/cartoes/',
  path: '/cartoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosIndexRoute = GastosIndexRouteImport.update({
  id: '/gastos/',
  path: '/gastos/',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosIdRoute = GastosIdRouteImport.update({
  id: '/gastos/$id',
  path: '/gastos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosNovoRoute = GastosNovoRouteImport.update({
  id: '/gastos/novo',
  path: '/gastos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gastos/$id': typeof GastosIdRoute
  '/gastos/novo': typeof GastosNovoRoute
  '/cartoes/': typeof CartoesIndexRoute
  '/gastos/': typeof GastosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gastos/$id': typeof GastosIdRoute
  '/gastos/novo': typeof GastosNovoRoute
  '/cartoes': typeof CartoesIndexRoute
  '/gastos': typeof GastosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gastos/$id': typeof GastosIdRoute
  '/gastos/novo': typeof GastosNovoRoute
  '/cartoes/': typeof CartoesIndexRoute
  '/gastos/': typeof GastosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gastos/$id' | '/gastos/novo' | '/cartoes/' | '/gastos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gastos/$id' | '/gastos/novo' | '/cartoes' | '/gastos'
  id:
    '__root__' | '/' | '/gastos/$id' | '/gastos/novo' | '/cartoes/' | '/gastos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GastosIdRoute: typeof GastosIdRoute
  GastosNovoRoute: typeof GastosNovoRoute
  CartoesIndexRoute: typeof CartoesIndexRoute
  GastosIndexRoute: typeof GastosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes/': {
      id: '/cartoes/'
      path: '/cartoes'
      fullPath: '/cartoes/'
      preLoaderRoute: typeof CartoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos/': {
      id: '/gastos/'
      path: '/gastos'
      fullPath: '/gastos/'
      preLoaderRoute: typeof GastosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos/$id': {
      id: '/gastos/$id'
      path: '/gastos/$id'
      fullPath: '/gastos/$id'
      preLoaderRoute: typeof GastosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos/novo': {
      id: '/gastos/novo'
      path: '/gastos/novo'
      fullPath: '/gastos/novo'
      preLoaderRoute: typeof GastosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GastosIdRoute: GastosIdRoute,
  GastosNovoRoute: GastosNovoRoute,
  CartoesIndexRoute: CartoesIndexRoute,
  GastosIndexRoute: GastosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
